[build]
  command = "npm run build"
  publish = "/build"
  base = "/"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  
  [redirects.headers]
    Referer="https://day-accounting.netlify.app/"
